### ISSUE TITLE
Реализовать функции администрирования кластеров баз данных: добавить

### ISSUE THREAD

**Issue by mgerasim** [mgerasim/pg_profile-devel#2]
https://github.com/mgerasim/pg_profile/projects/1#card-7775276

**Comment by mgerasim** [comment]
Андрей @zubkov-andrei , реализовал этот функционал на ветке Issue2 https://github.com/mgerasim/pg_profile-devel/tree/Issue2

прошу проверить на предмет логики и стилистики

**Comment by zubkov-andrei** [comment]
Посмотрел. Нашел наверняка не все, но вот что точно надо поправить:

1. Расширение может быть установлено не в схему public. Более того, это рекомендуемый вариант. Чтобы функции расширения могли найти остальные объекты этого расширения (таблицы, вьюхи, функции...), необходимо использовать конструкцю **SET search_path=@extschema@,public** в объявлении каждой функции. (См. доку по разработке расширений)
2. На мой взгляд как-то странно выглядят отступы... В редакторе, наверное лучше, там, судя по всему, используется табуляция. Я свой редактор настраиваю на то чтобы вместо табуляции он расставлял определенное количество пробелов, иначе код обязательно разъедется у кого-нибудь.
3. Не понял зачем нужна функция добавления "своего" кластера. Это должно выполняться один раз при установке расширения. Не думаю что для этого стоит создавать отдельную функцию.
4. Считаю что было бы удобно для параметра connect_port функции cluster_add назначить значение по умолчанию для параметров connect_port и database в 5432 и postgres соответственно, как наиболее вероятные в использовании. Если эти параметры сделать последними в объявлении функции (как необязательные), но не надо будет создавать несколько функций. Это будет выглядеть не очень логично, но будет сильно проще. Также необязательным стоит сделать description.
5. Я бы еще добавил в табличку что-то вроде краткого названия (напр. name), которое было бы обязательным и по которому можно будет выполнять, например, сбор отчета. Не по ID же его делать, и не по адресу с портом или описанию.
6. В перспективе, надо будет написать функции для удаления и редактирования кластеров. А также для включения и выключения сбора статистик по кластеру (для этого опять потребуется поле в таблице кластеров).

**Comment by mgerasim** [comment]
1.Расширение может быть установлено не в схему public. Более того, это рекомендуемый вариант. Чтобы функции расширения могли найти остальные объекты этого расширения (таблицы, вьюхи, функции...), необходимо использовать конструкцю SET search_path=@extschema@,public в объявлении каждой функции. (См. доку по разработке расширений)

Принято, к сведению. На данный момент используется конструкция 
SET search_path=public
при разработке модуля компоновки - будет автоматически заменена на 
SET search_path=@extschema@,public
https://github.com/mgerasim/pg_profile-devel/commit/d9e30f5feb98a90167f6627963dff35051c85e61

2.На мой взгляд как-то странно выглядят отступы... В редакторе, наверное лучше, там, судя по всему, используется табуляция. Я свой редактор настраиваю на то чтобы вместо табуляции он расставлял определенное количество пробелов, иначе код обязательно разъедется у кого-нибудь.

https://github.com/mgerasim/pg_profile-devel/commit/363522cb68907b3f8962b620d90669221c62b3b5

3.Не понял зачем нужна функция добавления "своего" кластера. Это должно выполняться один раз при установке расширения. Не думаю что для этого стоит создавать отдельную функцию.

Вопрос пересмотрел. Удалена. 
https://github.com/mgerasim/pg_profile-devel/commit/02a861f209b2c35beb53ef8d35d7fde24d03a26b

4.Считаю что было бы удобно для параметра connect_port функции cluster_add назначить значение по умолчанию для параметров connect_port и database в 5432 и postgres соответственно, как наиболее вероятные в использовании. Если эти параметры сделать последними в объявлении функции (как необязательные), но не надо будет создавать несколько функций. Это будет выглядеть не очень логично, но будет сильно проще. Также необязательным стоит сделать description.

Добавлены значения по умолчанию для порта и имени БД. Поле для описание удалено, так как вероятность его использования мала. Назначение кластера можно задать в уникальном имени кластера. 
https://github.com/mgerasim/pg_profile-devel/commit/83d92c8d1868dc1e7c552b366b53c597509a8c7b
В рамках #7 Заменить последовательность параметров connect_port и connect_database предлагается изменить описание функция по добавлению и редактированию кластера


5.Я бы еще добавил в табличку что-то вроде краткого названия (напр. name), которое было бы обязательным и по которому можно будет выполнять, например, сбор отчета. Не по ID же его делать, и не по адресу с портом или описанию.

Добавлено уникальное поле name. 
В рамках #8 Учитывать регистр для поля name таблицы clusters при проверки на уникальность, предлагается рассмотреть проверка уникальности имени кластера баз данных с учетом регистра

6.В перспективе, надо будет написать функции для удаления и редактирования кластеров. А также для включения и выключения сбора статистик по кластеру (для этого опять потребуется поле в таблице кластеров).

Функция удаления реализовывается в рамках #3 https://github.com/mgerasim/pg_profile-devel/commits/issue3
Функция редактирование - в рамках #4 https://github.com/mgerasim/pg_profile-devel/commits/issue4
Функция для включения и выключения сбора статистик по кластеру  -  в рамках #5 90b4ea6b8d8aa24f230f85776155c7032519309a

**Comment by zubkov-andrei** [comment]
Общие соображения изложены в #5
