### ISSUE TITLE
Реализовать функции администрирования кластеров баз данных: удалить

### ISSUE THREAD

**Issue by mgerasim** [mgerasim/pg_profile-devel#3]
https://github.com/mgerasim/pg_profile/projects/1#card-7775276

**Comment by mgerasim** [comment]
Андрей @zubkov-andrei , реализовано на ветке issue3 - прошу проинспектировать на соответствие функционалу и стилистике

**Comment by zubkov-andrei** [comment]
Стоит обратить внимание на комент #5
