### ISSUE TITLE
Заменить последовательность параметров connect_port и connect_database 

### ISSUE THREAD

**Issue by mgerasim** [mgerasim/pg_profile-devel#7]
Заменить последовательность параметров connect_port и connect_database в функциях cluster_add и cluster_edit, так как вероятность использования имени базы данных, отличное по умолчанию 'postgres' выше, чем использование нестандартного порта.

**Comment by mgerasim** [comment]
Андрей @zubkov-andrei на сколько это актуально?

**Comment by zubkov-andrei** [comment]
Тут дело тёмное что вероятнее... Пожалуй, нестандартный порт вероятнее, поскольку база postgres, обычно есть у всех, и поскольку нам нужен суперпользовательский коннект, никаких проблем с использованием именно этой базы я не вижу. Честно признаться, я вообще сомневаюсь что кому-то когда-то придет в голову использовать какую-то другую базу. Нам все равно нужен заход во все базы кластера.

**Comment by mgerasim** [comment]
Отклонен
